### ISSUE TITLE
Dataset JSON Format Example?

### ISSUE THREAD

**Issue by marvinstanley** [aqweteddy/NRMS-Pytorch#1]
Hello,

As the title suggests, could you give me a small sample of the articles.json and user_lists.json used so I can use it as an example to create my own dataset?

Thanks in advanced

**Comment by aqweteddy** [comment]
OK, I have written the data description in README.md.

**Comment by marvinstanley** [comment]
Okay, thanks for the help. The description provided is very helpful.

Closing the issue.
